### ISSUE TITLE
portfinder returning EADDRNOTAVAIL whether 27017 is available or not

### ISSUE THREAD

**Issue by azhang** [mccormicka/Mockgoose#196]
Tue, 01 Mar 2016 00:05:09 GMT Mockgoose dbpath: /home/ubuntu/project-api/node_modules/mockgoose/.mongooseTempDB
Tue, 01 Mar 2016 00:05:09 GMT Mockgoose Starting to look for available port, base: 127.0.0.1:27017
Tue, 01 Mar 2016 00:05:09 GMT Mockgoose error from portfinder: { [Error: listen EADDRNOTAVAIL ::1:27017]

On Circleci, I'm getting these errors regardless of whether something is using 27017 or not. I can manually run node_modules/mongodb-prebuilt/mongod and it works on 27017

**Comment by winfinit** [comment]
@azhang what OS are you using? also mongod by default is binding to 0.0.0.0, so that does NOT mean bind to all available interfaces on every operating system, so for example, if you have something running on 27017 on public or local interface, but not home, mongod will successfully start on OS X for example, however "port finder" will correctly report 27017 as busy, because it will be looking for an IP that is available across all of your network interfaces.

**Comment by azhang** [comment]
Circleci runs Ubuntu 12.04

**Comment by winfinit** [comment]
@azhang ahhh, i think i see whats going on, let me look at it more, it is complaining about ::1 which is ipv6, so if that is not enabled, portfinder will throw an error, which makes sense, so portfinder needs to test for ipv6 availability before adding ::1 to a test. 

thank you for this report, this is going to be fun

**Comment by azhang** [comment]
Oh awesome, that makes sense. Thanks for the quick response!

**Comment by jprempeh** [comment]
Hi there. I have the same issue when I used mockgoose with my test suite and deploy to circleCI. I get the following error: 

`  1) "before all" hook

  0 passing (10ms)
  1 failing

  1)  "before all" hook:
     Uncaught Error: listen EADDRNOTAVAIL
      at errnoException (net.js:904:11)
      at Server._listen2 (net.js:1023:19)
      at listen (net.js:1064:10)
      at net.js:1146:9
      at dns.js:72:18`

When I stripped out mockgoose, everything worked just fine.

**Comment by azhang** [comment]
Can confirm. If I change node_modules/portfinder/lib/portfinder.js:79

    var hosts = [‘::1’, ‘127.0.0.1’, ‘0.0.0.0’]

to 

    var hosts = [‘127.0.0.1’, ‘0.0.0.0’]

it works.

**Comment by winfinit** [comment]
@azhang correct, thats the gist of the issue. it can be tracked here: https://github.com/indexzero/node-portfinder/issues/26 I believe @erictrom is working on it.

**Comment by eriktrom** [comment]
@azhang, @jprempeh  - if you want to try out https://github.com/indexzero/node-portfinder/pull/29 this should be fixed. Will merge after I get verification from someone, thanks! (leave results on that pr)

**Comment by eriktrom** [comment]
fixed in portfinder 1.0.3, if your using `^1.0.2` changes will come when pushed to npm, i dont have push access for that, but it will come at some point on its own

**Comment by azhang** [comment]
Yep, I just ran `npm install indexzero/node-portfinder` on circleci to get master and ran my tests with mockgoose. All good! Thanks!

**Comment by johntangma** [comment]
@azhang
I still experience this issue.

```Uncaught exception: Error: listen EADDRNOTAVAIL ::1:27017```

Can you post your circle.yml file?
How can I free port 27017?

**Comment by eriktrom** [comment]
the next version of portfinder is not published to npm - sorry i don't have control over that, it'll be soon though i'm sure - for now can you try with `indexzero/node-portfinder#master`? 

(if that doesn't work, let me know for sure, thanks :) )

**Comment by winfinit** [comment]
@eriktrom was just about to post that! @johntangma when new version is going to get published, I will update dependency version.

**Comment by azhang** [comment]
@johntangma under `dependencies`, I have 

dependencies:
  cache_directories:
    - node_modules
  override:
    - npm install
    - npm install indexzero/node-portfinder # temporary - update mockgoose when node-portfinder@1.0.3 is out. https://github.com/mccormicka/Mockgoose/issues/196
    - sudo stop mongodb

**Comment by johntangma** [comment]
```npm install indexzero/node-portfinder```
I already have tried this on circleci but still experience the problem.

**Comment by eriktrom** [comment]
try this port - travis does not have them all open 

`32768`

**Comment by azhang** [comment]
@johntangma did you do the `sudo stop mongodb` line? You might want to ssh in and debug manually. I'm not sure - the `npm install indexzero/node-portfinder` and `sudo stop mongodb` lines fixed it for me.

**Comment by winfinit** [comment]
@eriktrom that actually shouldn't matter, mockgoose will circle through ports to find an open one by using portfinder, so I think something else is going on there, if it would help, i can publish rc of mockgoose with port-finder dependency from github

**Comment by eriktrom** [comment]
also the new version would remove `::1` and retry meaning you should not get an exception for interface `::1` ever anymore - you may get one, but for 127.0.0.1 or 0.0.0.0 but not `::1` - perhaps you installed it wrong?

**Comment by eriktrom** [comment]
@winfinit - sure

**Comment by winfinit** [comment]
@johntangma try updating temporarily mockgoose to mockgoose@5.4.0-rc.1

**Comment by johntangma** [comment]
```Uncaught exception: ReferenceError: error is not defined
    at /home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/lib/portfinder.js:127:25
    at /home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/node_modules/async/lib/async.js:264:21
    at /home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/lib/portfinder.js:103:16
    at Server.onError (/home/ubuntu/backend/node_modules/mockgoose/node_modules/portfinder/lib/portfinder.js:42:14)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:95:17)
    at net.js:1025:14
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

I got this error when I try ```mockgoose@5.4.0-rc.1```

**Comment by eriktrom** [comment]
@johntangma - fixed and merged - install master again - you will get an error - but im curious what it is - did you pass in a host explicitly (thanks for letting me know, i had a typo error instead of err)

**Comment by johntangma** [comment]
```
Uncaught exception: Error: listen EADDRNOTAVAIL
```
Now I get this error  instead of 
```
Uncaught exception: Error: listen EADDRNOTAVAIL ::1:27017
```

**Comment by eriktrom** [comment]
try running this on the machine your using (if its travis then write a test)

```
    // http://www.toptip.ca/2010/02/linux-eaddrnotavail-address-not.html
    // cat /proc/sys/net/ipv4/ip_local_port_range
    var exec = require('child_process').exec;
    exec('cat /proc/sys/net/ipv4/ip_local_port_range', function(error, stdout, stderr) {
        console.log('stdout:', stdout);
        console.log('stderr:', stderr);
        if (error !== null) {
          console.log('exec error:', error);
        }
    });

```

**Comment by johntangma** [comment]
I am testing on CircleCI connected via ssh

**Comment by eriktrom** [comment]
just run this: `cat /proc/sys/net/ipv4/ip_local_port_range`

**Comment by johntangma** [comment]
cat /proc/sys/net/ipv4/ip_local_port_range

I tried to run this command on CircleCI shell and I got  ```32768	61000```

**Comment by eriktrom** [comment]
how are you using portfinder? should be `portfinder.getPort({ port: '32768`, host: 'localhost' })` in this case b/c 27017 is not open for sure (although it should iterate those 5,000 ports and find it for you, make sure your passing in a host that is known to exist as well (it does not iterate hosts, only ports for 127.0.0.1 and 0.0.0.0 (and ::1 but that seems to be not an option)

**Comment by johntangma** [comment]
I dont use  portfinder at all. I think mockgoose uses portfinder, no?

**Comment by eriktrom** [comment]
yeah - thats what i pushed upstream just now - and thats where that error you posted came from - so make sure to re-install that with #master at the end `npm i --save portfinder@indexzero/node-portfinder#master`

**Comment by johntangma** [comment]
`Uncaught exception: Error: listen EADDRNOTAVAIL`
Still same error.

```
import mongoose from 'mongoose';
import mockgoose from 'mockgoose';

mockgoose(mongoose);

mongoose.connect(process.env.MONGO_URI);

```

This is how I use mockgoose. And it works fine on local environment.
MONGO_URI is mongodb server on external host.

**Comment by eriktrom** [comment]
hmm - sorry im not sure I can help much past this point - perhaps @winfinit can help you when he's around - im not familiar with mockgoose - also what version of node are you using - there should be an address available in the longer stacktrace 

such as

```
{ [Error: listen EADDRNOTAVAIL ::1:8000]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '::1', <-- here 
  port: 8000 }
```

**Comment by johntangma** [comment]
```
Mockgoose error from portfinder: +2s { [Error: listen EADDRNOTAVAIL]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen' }
```

This is detailed error log I get using `DEBUG=*` environment variable

**Comment by eriktrom** [comment]
are you using node 0.10.*

**Comment by johntangma** [comment]
I am using node 5.1.0

**Comment by eriktrom** [comment]
hmm - we'll have to look further next week - but that is good to know that you don't get an `address` property b/c that's important

@winfinit - when you get a chance can you log internally inside of portfinder from your guys setup and tell me what you find next week, thanks man

**Comment by johntangma** [comment]
`mockgoose@5.4.0-rc.1`
There were problems with environment variables and this version solved the problem for me.
Thank you @eriktrom 
When do you think I can get official npm module for this fix?

**Comment by eriktrom** [comment]
oh sweet

as far as the push to npm - i cant say - its not my call - usually the repo owner checks in once a week

**Comment by azhang** [comment]
@winfinit portfinder 1.0.3 has been released! ^_^

**Comment by winfinit** [comment]
@azhang thank you, just published 5.4.0 to npm, after verifying that issue is gone, please don't forget to close this ticket. thanks again!
